- hosts: all
  sudo: true
  user: vagrant
  roles:
    - role: ntp
  tasks:
    - name: Install EPEL repo.
      yum:
        name: epel-release
        state: present

    - name: Install libs
      yum: name={{ item }} state=latest
      with_items: 
        - git 
        - freetds-devel 
        - readline-devel 
      
    - name: copy i18n
      template: src=templates/i18n dest=/etc/sysconfig/i18n mode=0644

    - name: copy freetds.conf 
      template: src=templates/freetds.conf dest=/etc/freetds.conf mode=0644

